config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  post 'offer' => 'home#offer'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index

  end


  def offer
    invite = params['interest']
    date = params['date']
    place = params['place']
    CoffeeMailer.sample_email(invite, params['description'], date, place).deliver
    redirect_to root_path, notice: 'Thank You for your reply.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section id="portfolio" class="bg-light-gray">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading">Coffee</h2>

        <h3 class="section-subheading text-muted">Is coffee meeting that much important?</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal">
          <!--<div class="portfolio-hover">-->
            <!--<div class="portfolio-hover-content">-->
              <!--<i class="fa fa-plus fa-3x"></i>-->
            <!--</div>-->
          <!--</div>-->
          <%= image_tag "p2.jpg", class: 'img-responsive' %>
        </a>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal">
          <!--<div class="portfolio-hover">-->
            <!--<div class="portfolio-hover-content">-->
              <!--<i class="fa fa-plus fa-3x"></i>-->
            <!--</div>-->
          <!--</div>-->
          <%= image_tag "p4.jpg", class: 'img-responsive' %>
        </a>
      </div>
      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal">
          <!--<div class="portfolio-hover">-->
            <!--<div class="portfolio-hover-content">-->
              <!--<i class="fa fa-plus fa-3x"></i>-->
            <!--</div>-->
          <!--</div>-->
          <%= image_tag "p5.jpg", class: 'img-responsive' %>
        </a>
      </div>
    </div>
  </div>
</section>



<%= render partial: 'shared/footer' %>



<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="modal-body">
              <!-- Project Details Go Here -->
              <h2>Coffee Party</h2>

              <p class="item-intro text-muted">Thank You for accepting my Invitation.</p>
              <i class="fa fa-coffee fa-5x"></i>

              <p>Your response will go straight to my Email address. Just fill the form below and join with me!</p>

              <form class="form-horizontal" action="<%= offer_path %>" method="post">
                <input type="hidden" value="1" name="interest">
                <div class="form-group">
                  <label for="inputEmail1" class="col-sm-2 control-label">Date</label>
                  <div class="col-sm-10">
                    <input required type="text" name="date" class="form-control" id="inputEmail1" placeholder="Date">
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputEmail2" class="col-sm-2 control-label">Place</label>
                  <div class="col-sm-10">
                    <input required type="text" name="place" class="form-control" id="inputEmail2" placeholder="Place">
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputPassword1" class="col-sm-2 control-label">Details</label>
                  <div class="col-sm-10">
                    <textarea required class="form-control" name="description" rows="3" id="inputPassword1" placeholder="Additional Comment"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10 text-right">
                    <button type="submit" class="btn btn-success">Accept</button>
                  </div>
                </div>
              </form>

              <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Portfolio Modal 2 -->
<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2">
            <div class="modal-body">
              <h2>No Party</h2>

              <p class="item-intro text-muted">Hard to believe you took this decision!</p>
              <i class="fa fa-exclamation-triangle fa-5x"></i>

              <p>Your response will go straight to my Email address. Just fill the form below and reject the offer!</p>

              <form class="form-horizontal" action="<%= offer_path %>" method="post">
                <input type="hidden" value="0" name="interest">
                <div class="form-group">
                  <label for="inputPassword2" class="col-sm-2 control-label">Why?</label>
                  <div class="col-sm-10">
                    <textarea name="description" required class="form-control" rows="3" id="inputPassword2" placeholder="Why???"></textarea>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-2 col-sm-10 text-right">
                    <button type="submit" class="btn btn-success">Reject</button>
                  </div>
                </div>
              </form>

              <button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Close
                Project
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
    $(function(){
        $(".intro-lead-in").typed({
            strings: ["It's Nice To Meet You", "I'm offering you a cup of Coffee"],
            typeSpeed: 0,
            loop: true
        });
    });
    $('#inputEmail1').datetimepicker({theme:'dark'});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoffeeOffer</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


  <!-- Custom Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Theme CSS -->

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js" integrity="sha384-0s5Pv64cNZJieYFkXYOTId2HMA2Lfb6q2nAcx2n0RTLUnCAoTTsS0nKEO27XyKcY" crossorigin="anonymous"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js" integrity="sha384-ZoaMbDF+4LeFxg6WdScQ9nnR1QC2MIRxA1O9KWEXQwns1G8UNyIEZIQidzb0T1fo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js" integrity="sha384-mE6eXfrb8jxl0rzJDBRanYqgBxtJ6Unn4/1F7q4xRRyIw7Vdg9jP4ycT7x1iVsgb" crossorigin="anonymous"></script>

</head>


<body id="page-top" class="index">

<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">Coffee Offer</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="page-scroll" href="#portfolio">Coffee</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<!-- Header -->
<header>
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"></div>
      <div class="intro-heading">Let's meet somewhere holding a cup of Coffee!</div>
      <a href="#portfolio" class="page-scroll btn btn-xl">Tell Me More</a>

      <div style="margin-top: 20px" class="row">
        <div class="col-md-6 col-xs-12 text-right">
          <a href="#portfolioModal1" data-toggle="modal" class="btn-success btn-lg"><i class="fa fa-thumbs-up"></i> I'm Interested</a>
        </div>
        <div class="col-md-6 col-xs-12 text-left">
          <a href="#portfolioModal2" class="btn-danger btn-lg" data-toggle="modal"><i class="fa fa-thumbs-down"></i> I'm NoT Interested</a>
        </div>

      </div>
    </div>
  </div>
</header>


<!-- Portfolio Grid Section -->

<%= yield %>

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; অভপাপ 2017</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li><a href="https://www.flickr.com/photos/ihossain/" target="_blank"><i class="fa fa-flickr"></i></a>
          </li>
          <li><a href="https://www.facebook.com/ihemu" target="_blank"><i class="fa fa-facebook"></i></a>
          </li>
          <li><a href="https://www.github.com/imtiaz-emu" target="_blank"><i class="fa fa-git"></i></a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li><a href="https://about.me/iemu" target="_blank">About Me</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>